//
//  CS_Localized_EN.swift
//  CrazySnake
//
//  Created by Lee on 28/03/2023.
//

import UIKit


let CS_Localized_EN = [
    
    "crazy_str_app_name":"Crazy Slither",

     "crazy_str_def_amount":"0.000000",
     "crazy_str_usdt":"USDT",
     "crazy_str_diamond":"Gas coin",
     "crazy_str_copied":"Copy succeeded",
     "crazy_str_copy_fail":"Copy fail",
     "crazy_str_ok":"Ok",
     "crazy_str_cancel":"Cancel",
     "crazy_str_complete_verify":"Complete verification",
     "crazy_comm_list_end":"  End  ",
     "crazy_str_events":"Events",
     "crazy_str_fun_games":"Fun Games",
     "crazy_str_battle":"Battle",

     //MARK:  Wallet  -->
     "crazy_str_my_wallet":"My Wallet",
     "crazy_str_receive":"Receive",
     "crazy_str_send":"Send",
     "crazy_str_polygon":"(Polygon)",
     "crazy_str_my_portfolio":"My portfolio",
     "crazy_str_import_wallet":"Import Wallet",
     "crazy_str_add_new_wallet":"Add New Wallet",

     //MARK:  send  -->
     "crazy_str_polygon_2":"Polygon",
     "crazy_str_current_network":"Current network",
     "crazy_str_transfer_out_amount":"Transfer out amount",
     "crazy_str_gass_fee":"Gas fee",
     "crazy_str_matic":"Matic",
     "crazy_str_receiving_wallet_address":"Receiving Wallet Address",
     "crazy_str_input_receiving_wallet_address":"Input Receiving Wallet Address",
     "crazy_str_sending_wallet_address":"Sending Wallet Address",
     "crazy_str_balance":"Balance",
     "crazy_str_snake":"Snake",
     "crazy_str_confirm_and_send":"Confirm and Send",
     "crazy_str_amount_hint":"Input Amount",

     //MARK:  send confirm  -->
     "crazy_str_confirm_and_send_1":"Confirm and Send?",

     //MARK:  error  -->
     "crazy_str_error_params_illegal":"Params Illegal",
     "crazy_str_error_sdk_resp_null":"System error",
     "crazy_str_error_product_info":"Product info error!",
     "crazy_str_error_consume_failed":"Consume failed!",

     //MARK:  pwd set  -->
     "crazy_str_pwd_set":"Set a payment password",
     "crazy_str_pwd_verify":"Verify a payment password",
     "crazy_str_pwd_set_desc":"6-digit security code This password will be used for wallet related transactions",
     "crazy_str_pwd_confirm_desc":"Enter the password again to verify",


     //MARK:  receive  -->
     "crazy_str_import_qr_code_address":"Import QR code address",
     "crazy_str_save_qr_code":"Save QR Code",
     "crazy_str_copy_address":"Copy Address",
     "crazy_str_save_success":"Save Successful",
     "crazy_str_save_error":"Save Error",
     "crazy_str_error":"Error",

     //MARK:  setting  -->
     "crazy_str_setting":"Setting",
     "crazy_str_setting_wallet_address_label":"Wallet Address:",
     "crazy_str_set_payments_password":"Set a payments Password",
     "crazy_str_change_payments_password":"Change payments password",
     "crazy_str_set_payments_desc":"A secure password ensures trading safety",
     "crazy_str_backup_phrase_and_private_key":"Backup Secret Recovery Phrase and Private Key",
     "crazy_str_backup_phrase_and_private_key_desc":"Ensure it is hidden in a secure location on an offline physical device.",

     //MARK:  create wallet  -->
     "crazy_str_create":"Create",
     "crazy_str_mnemonic":"Mnemonic",
     "crazy_str_private_key":"Private Key",
     "crazy_str_copy":"Copy",
     "crazy_str_create_wallet_desc":"Your Secret Pecovery Phrase makes it easy to back up and restor",
     "crazy_str_verify_later":"Verify later",
     "crazy_str_confirm_right_now":"Confirm right now",

     //MARK:  create import  -->
     "crazy_str_enter_mnemonics_or_secret_label":"Enter mnemonics or private key",
     "crazy_str_enter_mnemonics_or_secret_desc":"Separate mnemonics with spaces. Support 12-word mnemonic import, support plaintext private key import.",
     "crazy_str_import":"Import",
     "crazy_str_enter_mnemonics_or_secret_warning":"Warning: Use only Wallets Supporting",

     //MARK:  back up  -->
     "crazy_str_backup":"Backup",
     "crazy_str_backup_label":"Backup your wallet information",
     "crazy_str_backup_desc":"Your Secret Pecovery Phrase makes it easy to back up and restore your account",
     "crazy_str_backup_hint":"Separate mnemonics with spaces. Support 12-word mnemonic import, support plaintext private key import.",
     "crazy_str_backup_warning":"WARNING: Never disclose your Secret Recover Phrase. Anyone with this phrase can take your assets forever",

     //MARK:  back up confirm -->
     "crazy_str_backup_confirm":"Backup Confirm",
     "crazy_str_backup_confirm_label":"Verify your private KEY",
     "crazy_str_backup_confirm_desc":"Please select each word in order to make sure it is correct, and store it in a secure location.",
     "crazy_str_backup_confirm_hint":"Please input private KEY",
     "crazy_str_backup_confirm_warning":"WARNING: Never disclose your Secret Recover Phrase. Anyone with this phrase can take your assets forever",

     //MARK:  backup mnemonic verify -->
     "crazy_str_backup_mnemonic_verify_label":"Verify your private KEY",
     "crazy_str_backup_mnemonic_verify_desc":"Please select each word in order to make sure it is correct, and store it in a secure location.",

     //MARK:  upgrade -->
     "crazy_str_upgrade_nft":"NFT Upgrade",
     "crazy_str_choose_nft_to_upgrade":"Choose NFT to upgrade",
     "crazy_str_empty":"Empty",
     "crazy_str_empty_nfg_hint":"No NFTs available in your inventory",
     "crazy_str_empty_nft_backpack_hint":"No active offers",
     "crazy_str_level_def":"Lv.%s",
     "crazy_str_switch":"Switch",
     "crazy_str_zero":"0",
     "crazy_str_nft_upgrade_desc":"One feed pack (experience points)",
     "crazy_str_max":"MAX",
     "crazy_str_speed_up":"Speed up",
     "crazy_str_buy":"Buy",
     "crazy_str_my_food_packs":"My feed packs",
     "crazy_str_owned":"Owned",
     "crazy_str_level_up":"Upgrade!",
     "crazy_str_upgrade":"Evolution!",
     "crazy_str_level":"Level",
     "crazy_str_hash":"Hash",

     //MARK: Dialog -->
     //MARK: set payment password -->
     "crazy_str_dialog_set_payment_password_desc":"The system noticed that you have not set a payment password for your account. For your account, wallet, and funds protection, please set a payment password to perform future actions.",
     "crazy_str_dialog_set_payment_password_btn":"Set now!",
     //MARK: backup reminder -->
     "crazy_str_backup_reminder":"Backup reminder",
     "crazy_str_skip":"Skip",
     "crazy_str_dialog_backup_reminder_desc":"Your wallet address has not been backed up for the mnemonic phrase. In order to prevent the loss of assets caused by forgetting the password, deleting the APP or losing the mobile phone, please be sure to back up the mnemonic phrase!",

     //MARK: NFT Stake -->
     "crazy_str_nft_stake":"NFT Stake",
     "crazy_str_all":"All",
     "crazy_str_single":"Single",
     "crazy_str_set":"Set",
     "crazy_str_total_hash_power":"Total Hash Power",
     "crazy_str_staked_amount":"Staked Amount",
     "crazy_str_my_hash_power":"My Hash power",
     "crazy_str_staking_slot_bonus":"Staking slot bonus",
     "crazy_str_total_rewards":"Total Rewards",
     "crazy_str_claims":"Claim",
     "crazy_str_initial_hash_power":"Initial Hash power",
     "crazy_str_set_hash_power_bonus":"Set Hash Power Bonus",

     //MARK: Single Stake -->
     "crazy_str_choose_single_nft":"Choose Single NFT",
     "crazy_str_choose_nft_set":"Choose NFT Set Quick select",
     "crazy_str_choose_nft_set_manual":"Choose NFT Set      Manual selection",
     "crazy_str_stake":"Stake",

     //MARK:market-->
     "crazy_str_market":"Market",
     "crazy_str_market_selling":"Selling",

     //MARK:NFT Lab-->
     "crazy_str_nft_lab":"NFT Lab",
     "crazy_str_nft_level_up":"Upgrade",
     "crazy_str_nft_upgrade":"Evolution",
     "crazy_str_nft_recycle":"Conversion",
     "crazy_str_nft_transform":"Transform",
     "crazy_str_nft_incubation":"Incubation",
     "crazy_str_nft_upgrade_orb":"Upgrade Orb",
     "crazy_str_nft_upgrade_stage":"Upgrade stage",
     "crazy_str_nft_hash_bonus":"Hash bonus",
     "crazy_str_nft_choose_nft":"Choose NFT",
     "crazy_str_nft_choose_incubator":"Choose Incubator",
     "crazy_str_nft_incubation_time":"Incubation time:",
     "crazy_str_nft_Incubation_times":"Incubation times",
     "crazy_str_nft_incubation_time_desc":"1 Hourglass",
     "crazy_str_nft_incubation_completed":"INCUBATION COMPLETED",
     "crazy_str_nft_open":"Open",
     "crazy_str_nft_incubation_time_spent":"Time spent",
     "crazy_str_nft_incubation_end_time":"End time:",
     "crazy_str_nft_incubation_see_more":"See more",
     "crazy_str_nft_incubation_see_more_desc":"Congratulations on getting an NFT, see more on My NFT",
     //MARK:my nft-->
     "crazy_str_my_nft":"My NFTs",
     "crazy_str_nft_list":"NFT List",
     "crazy_str_backpack":"Backpack",
     "crazy_str_upgrade_stage":"Upgrade stage",
     "crazy_str_hash_power":"Hash Power",
     "crazy_str_sell":"Sell",
     "crazy_str_use":"Use",

     //MARK:nft stake-->
     "crazy_str_nft_stake_list":"NFT Staking list",
     "crazy_str_nft_stake_single_nft":"Single NFT",
     "crazy_str_nft_stake_nft_set":"NFT Set",
     "crazy_str_staking":"Staking",
     "crazy_str_empty_click_close":"Click on blank space to close",
     "crazy_str_nft_stake_set_desc":"When staking an NFT set you need at least 3 NFTs of different qualities.",
     "crazy_str_nft_stake_my_nfts":"My NFTs ",
     "crazy_str_nft_stake_set_name":"Set Name",
     "crazy_str_nft_stake_action":"Action",
     "crazy_str_claim":"Claim",
     "crazy_str_stake_now":"Stake now",
     "crazy_str_set_needed":"Set needed",
     "crazy_str_select":"Select",
     "crazy_str_selected":"Selected",
     "crazy_str_start_time":"Start time",
     "crazy_str_staking_earnings":"Staking Earnings",
     "crazy_str_nft_sets":"NFT Sets",
     "crazy_str_un_stakes":"Un Stakes",

     //MARK:swap-->
     "crazy_str_swap":"Swap",
     "crazy_str_pay":"Pay",
     "crazy_str_get":"Get",
     "crazy_str_refresh_price":"Refresh price",
     "crazy_str_confirm_swap":"Confirm Swap",
     "crazy_str_slippage":"Slippage",
     "crazy_str_fees":"Fees",
     "crazy_str_conversion":"Conversion",
     "crazy_str_price":"Price",
     "crazy_str_from":"From",
     "crazy_str_to":"To",
     //MARK:currency stake-->
     "crazy_str_token_stake":"Token Stake",
     "crazy_str_input_staking_amount":"Input Staking Amount",
     "crazy_str_select_time":"Select Time",
     "crazy_str_cyt_quantity":"CYT Quantity (CYT)",
     "crazy_str_confirm_and_stake":"Confirm And Stake",
     "crazy_str_short":"Short",
     "crazy_str_meduim":"Meduim",
     "crazy_str_long":"Long",
     "crazy_str_7_day":"7 Day",
     "crazy_str_14_day":"14 Day",
     "crazy_str_1_month":"1 Month",
     "crazy_str_3_month":"3 Month",
     "crazy_str_6_month":"6 Month",
     "crazy_str_1_year":"1 Year",
     "crazy_str_2_year":"2 Year",
     "crazy_str_3_year":"3 Year",

     "crazy_str_total_number_of_pledges":"Total number of pledges",
     "crazy_str_total_amount_of_cyt":"Total amount of CYT",
     "crazy_str_receive_cyt_amount":"Receive CYT amount:",
     "crazy_str_staking_time":"Staking time: ",
     "crazy_str_stake_start_time":"Stake start time:",
     "crazy_str_unlockin_time":"Unlocking time:",
     "crazy_str_my_token_stake":"My Token stake",
     "crazy_str_staking....":"Staking....",
     "crazy_str_estimated_fuel_cost":"Estimated Gas Fee Cost",
     "crazy_str_gas_fee":"Gas fee",
     "crazy_str_max_coins_needed":"Max Gas Coin needed",
     "crazy_str_remaining":"Remaining(GasCoin)",
     "crazy_str_contract_address":"Contract address",
     "crazy_str_reject":"Reject",
     "crazy_str_confirm":"Confirm",
     "crazy_str_inventory_is_empty":"Inventory is empty",
     "crazy_str_transfer":"Transfer",
     "crazy_str_approve":"Approve",
     "crazy_str_un_staking":"UnStaking",
     "crazy_str_see_your_nfts_here":"See your NFTs here",
     "crazy_str_quantity_for_sale":"Quantity",
     "crazy_str_i_know":"I know",
     "crazy_str_guide_desc":"Single currency staking can provide CYT. When you get CYT, you can get a better event gift bag at a lower price in the event. The event gift bag will contain some high-quality NFT or high-value material props",
     "crazy_str_guide_nft_stake_desc":"NFT staking is divided into individual and set staking. Any idle NFT can be staked individually. Set staking requires the same set of NFTs of different qualities to be staked at the same time. When teh set meets certain conditions, you can get a hash power bonus and get more rewards",
     "crazy_str_guide_token_stake_desc":"Single currency staking can provide CYT. When you get CYT, you can get a better event gift bag at a lower price in the event. The event gift bag will contain some high-quality NFT or high-value material props",
     "crazy_str_guide_wallet_desc":"In the wallet, you can view the assets you currently own, and you can also perform some backups, transfers, etc.",
     "crazy_str_guide_level_up_desc":"Upgrading can increase the level of NFT. The higher the level of NFT, the higher the hash power, and you can also get higher returns when NFT is staked",
     "crazy_str_guide_upgrade_desc":"Evolution can improve the NFT star rating. The higher the star rating, the higher the NFT hash power bonus, and you can also get higher returns when NFT is staked",
     "crazy_str_guide_recycle_desc":"Recycling can convert idle NFTs into evolutionary essence, which can be used for the evolution of NFTs",
     "crazy_str_guide_incubation_desc":"Use two NFTs of different genders to incubate, and you can get a brand new NFT. The higher the quality of the parents, the higher the quality of the hatched NFT.",
     "crazy_str_guide_market_desc":"1 The newly minted NFT will have a cooling time of 24 hours and cannot be put on the Marketplace during the cooling time\n2 A 3% handling fee will be charged when the transaction is successful in the market\n3 In the market, GASCOIN is required for the operation of delisting. GASCOIN can be obtained through exchange and diamond purchase in the game",


     //MARK:event-->
     "crazy_str_event":"Event",
     "crazy_str_gascoin":"Gascoin",
     "crazy_str_crazy_offers":"Crazy Offers",
     "crazy_str_amount_left":"Amount Left",
     "crazy_str_available":"Available",
     "crazy_str_end_time":"Event Time: %s",
     "crazy_str_event_old_price":"Price:%s",
     "crazy_str_event_discount":"%s\noff",
     "crazy_str_event_buy":"Buy",
     "crazy_str_incubation_list_empty":"only NFTs level 8 or above can be incubated",
     "crazy_str_token_stake_list_empty":"No token staking records",
     //MARK:-->
     "crazy_str_tip_application_init":"Please request when the application is created, CrazyPlatform.init(this) for initialization",


     "crazy_str_day":"Day",
     "crazy_str_month":"Month",
     "crazy_str_year":"Year",
     "crazy_str_tip_balance_empty":"balances need login",
     "crazy_str_tip_unknown_error":"unknown error",
     "crazy_str_tip_request_error":"Request failed",
     "crazy_str_tip_data_gson_error":"Error in data parsing, does not conform to the predetermined format",
     "crazy_str_tip_other_error":"unknown error",
     "crazy_str_tip_no_login":"Not signed in",
     "crazy_str_tip_login_error":"sign in failed, try again",
     "crazy_str_tip_wallet_chang":"switch wallet",
     "crazy_str_tip_blockchain_error":"blockchain error",
     "crazy_str_tip_success":"success",
     "crazy_str_tip_error":"error",
     "crazy_str_to_unlock_slot_u_need":"To unlock a slot you need:",
     "crazy_str_slot_card":"Slot card",
     "crazy_str_balance_":"Balance: ",
     "crazy_str_unlock_slot_card":"Unlock slot with Slot card",
     "crazy_str_balance_not_enough":"insufficient balance",
     "crazy_str_place_offer":"Place offer",
     "crazy_str_change_price":"Change price",
     "crazy_str_insufficient_inventory":"insufficient inventory",
     "crazy_str_current_purchasable_quantity":"The current available quantity is%s",
     "crazy_str_incubation":"Incubatin",
     "crazy_str_under_sale":"Selling",
     "crazy_str_At_least_three_or_more_can_pledged":"Minimum of 3 NFTs to stake",
     "crazy_str_you_can_only_pledge":"Up to 6 staking slots are allowed~",
     "crazy_str_gas_coin_not_enough":"Gas Coin not enough",
     "crazy_str_data_cannot_be_empty":"Data cannot be empty~",
     "crazy_str_data_mismatch":"Data mismatch~",
     "crazy_str_inoperable":"Inoperable~",
     "crazy_str_no_reward":"No reward~",
     "crazy_str_address_error":"Address error~",
     "crazy_str_common_incubator":"Common Incubator",
     "crazy_str_good_incubator":"Good Incubator",
     "crazy_str_excelent_incubator":"Excellent Incubator",
     "crazy_str_rare_incubator":"Rare Incubator",
     "crazy_str_epic_incubator":"Epic Incubator",
     "crazy_str_legendary_incubator":"Legendary Incubator",
     "crazy_str_upgrade_orb":"Upgrade Orb",
     "crazy_str_transform_orb":"Transform Orb",
     "crazy_str_simple_feed":"Simple Feed",
     "crazy_str_high_feed":"High Feed",
     "crazy_str_super_feed":"Super Feed",
     "crazy_str_hourglass":"Hourglass",
     "crazy_str_simple_box":"Simple Box",
     "crazy_str_common_box":"Common Box",
     "crazy_str_good_box":"Good Box",
     "crazy_str_excellent_box":"Excellent Box",
     "crazy_str_rare_box":"Rare Box",
     "crazy_str_epic_box":"Epic Box",
     "crazy_str_common_card_pack":"Common Card Pack",
     "crazy_str_incubation_for_common_nft":"Incubation for common NFT",
     "crazy_str_incubation_for_good_nfts":"Incubation for good NFTs",
     "crazy_str_incubation_for_excellent_nft":"Incubation for excellent NFT",
     "crazy_str_incubation_for_rare_nfts":"Incubation for rare NFTs",
     "crazy_str_incubation_for_epic_nft":"Incubation for epic NFT",
     "crazy_str_incubation_for_legend_nft":"Incubation for legendary NFT",
     "crazy_str_consumable_materials_for_nft_evolution":"Consumable materials for NFT evolution",
     "crazy_str_nft_advanced_consumable_materials":"NFT advanced consumable materials",
     "crazy_str_consumable_materials_for_nft_upgrades":"Consumable materials for NFT upgrades",
     "crazy_str_used_to_open_the_nft_staking_slot":"Used to open the NFT staking slot",
     "crazy_str_Accelerate_incubation_time_":"Accelerate the incubation time when used for NFT incubation",
     "crazy_str_super_cost_effective_mystery_box_":"Super cost-effective Mystery Box, 100% common NFT",
     "crazy_str_ordinary_quality_mystery_box_":"Good Mystery Box drop rate: Common - 10%, Good - 80%, High-grade Feed - 10%",
     "crazy_str_good_quality_mystery_box_":"Excellent Mystery Box drop rate: Good - 32%, Excellent - 68%",
     "crazy_str_excellent_quality_mystery_box_":"Rare Mystery Box drop rate: Good - 10%, Excellent - 50%, Rare - 40%",
     "crazy_str_mystery_box_of_rare_quality_":"Rare Mystery Box drop rate: Good - 10%, Excellent - 50%, Rare - 40%",
     "crazy_str_mystery_boxes_of_epic_quality_":"Epic Mystery Box drop rate: Excellent - 10%, Rare - 60%, Epic - 30%",
     "crazy_str_failed_to_load_click_retry":"Failed to load. Click Retry",
     "crazy_str_ball":"Ball",
     "crazy_str_item":"Item",
     "crazy_str_from_to":"From - to",
     "crazy_str_time":"Time",
     "crazy_str_incubator":"Incubator",
     "crazy_str_incubating__":"Incubating......",
     "crazy_str_congratulations_successful_incubation__":"Congratulations on your successful incubation! You just received a new NFT.",
     "crazy_str_when_incubating_crazy":"When incubating a Crazy NFT, you can use Hourglasses to decrease the incubation time.",


     "crazy_str_received":"Received",
     "crazy_str_please_select_nft":"Please select NFT~",
     "crazy_str_refresh":"Refresh",
     "crazy_str_nft":"NFT",
     "crazy_str_props":"Items",
     "crazy_str_inventory":"Inventory",
     "crazy_str_order_history":"Order history",
     "crazy_str_quality":"Quality",
     "crazy_str_reset":"Reset",
     "crazy_str_gender":"Gender",
     "crazy_str_boy":"Male",
     "crazy_str_girl":"Female",
     "crazy_str_empty_nft_list":"No NFTs to show. You can acquire NFTs by:\n1. Buying Mystery Box in NFT Shop\n2. Buying other players' NFT in the Market\n3. Buying Mystery Box periodically sold in Event",
     "crazy_str_orders_history":"Orders history",
     "crazy_str_data_of_swap":"Date of Swap",
     "crazy_str_pay_pay":"Pay",
     "crazy_str_get_get":"Get",
     "crazy_str_current_status":"Current Status",
     "crazy_str_input_payment_password":"Input payment password",
     "crazy_str_enter_the_password_to_verity":"Enter the password to verity",
     "crazy_str_send_order":"Send order",
     "crazy_str_understand":"Understand",
     "crazy_str_reviewing":"Reviewing",
     "crazy_str_waiting_for_blockchain_result_n":"Waiting for\nblockchain result",
     "crazy_str_waiting_for_blockchain_result":"Waiting for blockchain result",
     "crazy_str_confirming_transaction_n":"Confirming\ntransaction\n(ETA 48h)",
     "crazy_str_confirming_transaction":"Confirming transaction",
     "crazy_str_completed":"Completed",
     "crazy_str_cloose_single_nft":"Cloose Single NFT",
     "crazy_str_support_games":"Support games",
     "crazy_str_in_process":"In Process",
     "crazy_str_finished":"Finished",
     "crazy_str_insufficient_gas_coin":"Insufficient Gas Coin",
     "crazy_str_insufficient_gas_coin_desc":"1. You can swap for Gas Coin in Swap\n2. You can swap for GasCoin with Diamond in game",
     "crazy_str_swap_now":"Swap now!",

     "crazy_str_help_nft_stake":"1 On NFT Staking you can choose single or set staking\n2 There will be additional quality bonuses according to the quality and quantity of the selected NFTs when doing set staking\n2.1 When there are 3 NFTs of different qualities in a Stake set, an additional 20 hash power bonus can be obtained\n2.2  When there are 4 NFTs of different qualities in a Stake set, an additional 50 hash power bonus can be obtained\n2.1 When there are 5 NFTs of different qualities in a Stake set, an additional 150 hash power bonus can be obtained\n2.2  When there are 6 NFTs of different qualities in a Stake set, an additional 500 hash power bonus can be obtained\n3 The income from NFT staking will be distributed according to the proportion between your personal hash power  the total hash pwoer of the pool\n4 The number of daily staking rewards is determined by two factors. Rewards = the total hash power of NFTs staked (affects basic rewards) + platform game activity (affects additional rewards)\n5 The total hash power of NFT staking affects the number of basic rewards:\n0-----------100000 total hash will provide 6000 $Snake daily\n100001------200000 total hash will provide 10000 $Snake daily rewards\n200001------300000 total hash will provide  14000 $Snake daily rewards\n300001------500000 total hash will provide  22000 $Snake daily rewards\n500001------750000 total hash will provide  32000 $Snake daily rewards\n750001------1000000 total hash will provide  40000 $Snake daily rewards\n1000001-----3000000 total hash will provide  124000 $Snake daily rewards\n3000001-----6000000 total hash will provide  232000 $Snake daily rewards\n6000001-----10000000 total hash will provide  358000 $Snake daily rewards\n10000001+----unlimited basic rewards 500000 $Snake\n6. Platform game activity affects additional rewards: the higher the activity, the more additional rewards",
     "crazy_str_help_incubation":"1 Incubation requires two NFTs of different genders for incubation,\n2 Only when the NFT reaches level 8 or above can it participate in the incubation.\n3 Each NFT has a limit on the number of incubations. When the number of NFT incubations is 0, the NFT will not be able to participate in the incubation\n4 Incubation requires the use of an incubator. The quality of the incubator to be used is determined by the NFT with the highest quality among the two selected NFTs. The higher the quality of the incubator, the longer it will take to incubate\n5 The hourglass can be used to shorten the hatching time during the hatching process",
     "crazy_str_help_recycle":"1 Essence conversion can convert excess idle NFT into evolutionary essence, evolutionary essence can be used for the evolution of NFT, and NFT will get more computing power bonus after evolution\n2 The conversion of NFT into Evolutionary Essence is determined by the computing power of NFT itself and the quality of NFT. The higher the computing power, the more Evolutionary Essence will be converted, and additional essence will be provided according to the quality of NFT during conversion.",
     "crazy_str_help_token_stake":"1 When you stake your $Snake tokens, you can choose the locking period . After the locking period ends, you will get CYT. The number of CYT determines the number of personal subscriptions you can purchase platform gift packs in events. The more CYT you have, the more your purchase power you will have. \n2 When the lock-up period of your staked $snake is over, you can choose to withdraw the staked amount, which will not have any impact on the generated CYT",
     "crazy_str_help_swap_gas_coin":"1. Sending request to blockchain generates gasfee, which is related to the native token of the blockchain platform.\n2. To make it convenient, users can use GasCoin to pay the GasFee.",
     "crazy_str_help_event":"1. Gift packs sold in Event are limited and discounted.\n2. You need to stake token to get CYT, so to get qualification for purchase. The more CYT you possess, the more gift packs you can buy.",
     "crazy_str_help_market":"1 The newly minted NFT will have a cooling time of 24 hours and cannot be put on the Marketplace during the cooling time\n2 A 3% handling fee will be charged when the transaction is successful in the market\n3 In the market, GASCOIN is required for the operation of delisting. GASCOIN can be obtained through exchange and diamond purchase in the game",

     "crazy_str_congratulations":"Congratulations",
     "crazy_str_social":"Social",
     "crazy_str_support":"Support",
     "crazy_str_white_paper":"White paper",
     "crazy_str_twitter":"Twitter",
     "crazy_str_discord":"Discord",
     "crazy_str_telegram":"Telegram",
     "crazy_str_type":"Type",
     "crazy_str_crazy_box":"Crazy Box",
     "crazy_str_purchase_how_many":"Purchase how many?",
     "crazy_str_no_available":"Items left",
     "crazy_str_selling_price":"Selling price",
     "crazy_str_bought":"Bought",
     "crazy_str_sold":"Sold",
     "crazy_str_confirming":"Confirming",
     "crazy_str_input_the_item_price":"Input the item price(USD)",
     "crazy_str_sell_how_many":"Sell how many?",
     "crazy_str_sell_remove_offer":"Remove offer",
     "crazy_str_sell_stopping":"Stopping",
     "crazy_str_staking_reward":"Staking reward",
     "crazy_str_num_day":"%s Day",
     "crazy_str_num_month":"%s Month",
     "crazy_str_num_year":"%s Year",
     "crazy_str_sell_stop":"Take down",
     "crazy_str_fighting":"Fighting",
     "crazy_str_swap_u_min":"Minimum of 1 USDT to continue the operation",
     "crazy_str_token_stake_min":"Minimum of 200 $snake to continue the operation",
     "crazy_str_init_application":"Please use application when open,Perform %s",


     //MARK:play2earn-->
     "crazy_str_play_2_earn":"Play2earn",
     "crazy_str_quest":"Quest",
     "crazy_str_withdraw":"Withdraw",
     "crazy_str_newcomer_benefits":"Newcomer benefits",
     "crazy_str_cash_value":"Cash value",
     "crazy_str_more_ways_to_get":"More ways to get",
     "crazy_str_back_to_game":"Back to game",
     "crazy_str_watch_ads":"Watch ads",
     "crazy_str_game_recharge":"Game recharge",
     "crazy_str_invite_a_friend":"Invite a friend",
     "crazy_str_cyt":"CYT",
     "crazy_str_total_withdrawn":"Total withdrawn",
     "crazy_str_my_rewards":"My rewards",
     "crazy_str_my_invite_link":"My invite link",
     "crazy_str_invite_via":"Invite via",
     "crazy_str_today_rewards":"Today\'s Rewards",
     "crazy_str_see_more":"<u>See more</u>",
     "crazy_str_create_wallet":"Create wallet",
     "crazy_str_expected_to_receive":"Expected to receive",
     "crazy_str_withdraw_as":"Withdraw as",
     "crazy_str_detailed_information":"Detailed information",
     "crazy_str_friend":"Friend",
     "crazy_str_shared_today":"Shared today",
     "crazy_str_total_shared":"Total shared",
     "crazy_str_direct_share":"Direct share %s",
     "crazy_str_indirect_share":"Indirect share %s",
     "crazy_str_sure_to_proceed_with_the_conversion":"Sure to proceed with the conversion?",
     "crazy_str_help_swap_order_history_item_48h":"1 The exchange time displayed in the exchange history is based on the UTC time zone, so the time you see in the exchange history is not the time in your time zone, you need to confirm your current progress according to the time in the UTC time zone.\n2 The ETA time of receiving funds is a way to verify all transactions in the platform to ensure that the behavior of exchanging tokens is safe and effective, and we will not misappropriate any of your assets.",


     "crazy_str_snake_token_required":"Total Required",

     "crazy_str_share":"Share",
     "crazy_html_cash_value":"",
     "crazy_html_cyt":"CYT",
     "crazy_str_claimed":"Claimed",
     "crazy_str_earn_more":"Earn more",
     "crazy_str_watch_ads_desc":"Watching ads will generate a certain cash value, and it depends on the value of the ad.",
     "crazy_str_games_recharge_desc":"",
     "crazy_str_invite_a_friend_desc":"Invite a friend to receive more rewards",
     "crazy_str_invite_now":"Invite now",
     "crazy_html_miss_total_withdraw_cash_value":"",
     "crazy_str_history":"History",
     "crazy_str_withdraw_history":"Withdraw history",
     "crazy_str_date_of_withdraw":"Date of withdraw",
     "crazy_str_withdraw_amount":"Withdraw amount",
     "crazy_str_failed":"Failed",
     "crazy_str_processing":"Processing",
     "crazy_str_guess_the_size":"Luck Color",
     "crazy_str_rank":"Rank",
     "crazy_str_my_history":"My history",
     "crazy_str_description":"Description",
     "crazy_html_red_time":"",
     "crazy_html_blue_time":"",
     "crazy_html_supporters_num":"",
     "crazy_str_red":"Red",
     "crazy_str_blue":"Blue",
     "crazy_str_bidding_area":"Bidding Area",
     "crazy_str_input_support_amount":"Input Support Amount",
     "crazy_str_tip_support_agin":"Betting is currently unavailable, please refresh and try again～",
     "crazy_str_pool_size":"Pool size",
     "crazy_str_countdown":"Countdown",
     "crazy_str_round_ending_":"Ending",
     "crazy_str_round_no_open":"Unopened",
     "crazy_str_round_opening":"opening",
     "crazy_str_luck_team":"Luck Team",
     "crazy_str_red_team":"Red Team",
     "crazy_str_blue_team":"Blue Team",
     "crazy_str_random_value":"Random value",
     "crazy_str_biggest_winner":"Biggest Winner",
     "crazy_str_bet_bonus":"BET/bonus",
     "crazy_str_my_bet":"My BET",
     "crazy_str_status":"Status",
     "crazy_str_claim_all":"Claim ALL",
     "crazy_str_get_luck":"Get Luck",
     "crazy_str_no_luck":"No Luck",
     "crazy_str_haven_invited_friends_yet":"Haven\'t invited friends yet",
     "crazy_html_length_of_match":"",
     "crazy_str_no_rewards_claim":"No rewards to claim～",
     "crazy_str_no_records_to_show_at_the_moment":"No records to show",
     "crazy_str_no_activty":"No activity",
     "crazy_html_when_nft_set_directions":"",
     "crazy_str_set_pets":"Set pets",
     "crazy_str_collected":"Collected",
     "crazy_str_bet_min_num":"The bet amount cannot be less than %s",
     "crazy_str_bet_max_num":"The bet amount cannot be greater than %s",
     "crazy_str_bet_claim_num_min_max":"Withdrawal amount is less than %s, unable to withdraw",
     "crazy_str_help_guess_hot_play":"Hot to play: Choose a side to participate.\nAccording to the blockchain's smart contract to predict the score of the opponents.\nThe source of the predicted number size is provided by a third-party\noracle, Chainlink, to providea fair and simple environment for players.\nWinning is decided after the end of each round, two random numbers\nwill be obtained through Chainlink's Oracle, the first for the red team\nand the second for the blue team.Whoever has the highest number wins.",
     "crazy_str_help_share_cash_value":"1. The cash value is a stable currency that can be exchanged for USDT at a fixed ratio.\n2. Every time you successfully share with a friend, you will get cash value. When a friend downloads the app from your shared link, the friend relationship will be automatically bound.\n3. When the friends you invite and the next-level friends shared by your friends watch advertisements and recharge in the game, you will get additional sharing benefits. You can check it out at Today's Rewards-see more and Total Rewards-see more\\n4. Successfully bind the invitation relationship:\n4.1 New users have not installed crazy land platform devices\n4.2 Create wallet successfully",

     "crazy_str_transfer_records":"Transfer records",
     "crazy_str_transfer_to":"Transfer to",
     "crazy_str_amount":"Amount",
     "crazy_str_in_development":"In development. . .",
     "crazy_str_insufficient_quota":"Insufficient quota~",
     "crazy_str_view_more_details":"View more details",
     "crazy_str_shared_total":"Shared total",
     "crazy_str_portfolio":"Portfolio",
     "crazy_str_deposit":"Deposit",
     "crazy_str_after_listing":"After listing your NFT it won\'t be usable in the game. To use i",
     "crazy_str_list_nft":"List NFT",
     "crazy_str_my_wallet_address":"My wallet address",
     "crazy_str_gifted_wallet_address":"Gifted wallet address",
     "crazy_str_the_receiver_wallet_address":"The receiver wallet address must be a wallet from inside the ecosystem.",
     "crazy_str_send_now":"Send now",
     "crazy_str_input_wallet_address":"Input wallet address",
     "crazy_str_address_format_is_incorrect":"The address format is incorrect",
]

//class CS_Localized_EN: NSObject {
//
//}
