//
//  CS_Localized_CN.swift
//  CrazySnake
//
//  Created by Lee on 28/03/2023.
//

import UIKit

let CS_Localized_CN = [
    
    "crazy_str_app_name":"Crazy Slither",

    "crazy_str_def_amount":"0.000000",
    "crazy_str_usdt":"USDT",
    "crazy_str_diamond":"Gas coin",
    "crazy_str_copied":"複製成功",
    "crazy_str_copy_fail":"複製失敗",
    "crazy_str_ok":"Ok",
    "crazy_str_cancel":"取消",
    "crazy_str_complete_verify":"完成驗證",
    "crazy_comm_list_end":"結尾",
    "crazy_str_events":"事件",
    "crazy_str_fun_games":"趣味遊戲",
    "crazy_str_battle":"戰鬥",

    //MARK:Wallet  -->
    "crazy_str_my_wallet":"我的錢包",
    "crazy_str_receive":"收到",
    "crazy_str_send":"發送",
    "crazy_str_polygon":"(Polygon)",
    "crazy_str_my_portfolio":"我的投資組合",
    "crazy_str_import_wallet":"導入錢包",
    "crazy_str_add_new_wallet":"添加新錢包",

    //MARK:send  -->
    "crazy_str_polygon_2":"Polygon",
    "crazy_str_current_network":"當前網絡",
    "crazy_str_transfer_out_amount":"轉出金額",
    "crazy_str_gass_fee":"Gas fee",
    "crazy_str_matic":"Matic",
    "crazy_str_receiving_wallet_address":"接收錢包地址",
    "crazy_str_input_receiving_wallet_address":"輸入接收錢包地址",
    "crazy_str_sending_wallet_address":"發送錢包地址",
    "crazy_str_balance":"余额",
    "crazy_str_snake":"Snake",
    "crazy_str_confirm_and_send":"確認並發送",
    "crazy_str_amount_hint":"輸入量",

    //MARK:send confirm  -->
    "crazy_str_confirm_and_send_1":"確認並發送？",

    //MARK:error  -->
    "crazy_str_error_params_illegal":"非法參數",
    "crazy_str_error_sdk_resp_null":"系統錯誤",
    "crazy_str_error_product_info":"產品信息錯誤！",
    "crazy_str_error_consume_failed":"消費失敗！",

    //MARK:pwd set  -->
    "crazy_str_pwd_set":"設置支付密碼",
    "crazy_str_pwd_verify":"驗證支付密碼",
    "crazy_str_pwd_set_desc":"",
    "crazy_str_pwd_confirm_desc":"再次輸入密碼進行驗證",


    //MARK:receive  -->
    "crazy_str_import_qr_code_address":"導入二維碼地址",
    "crazy_str_save_qr_code":"保存二維碼",
    "crazy_str_copy_address":"複製地址",
    "crazy_str_save_success":"保存成功",
    "crazy_str_save_error":"保存錯誤",
    "crazy_str_error":"錯誤",

    //MARK:setting  -->
    "crazy_str_setting":"環境",
    "crazy_str_setting_wallet_address_label":"錢包地址：",
    "crazy_str_set_payments_password":"設置付款密碼",
    "crazy_str_change_payments_password":"更改支付密碼",
    "crazy_str_set_payments_desc":"安全密碼確保交易安全",
    "crazy_str_backup_phrase_and_private_key":"備份秘密助記詞和私鑰",
    "crazy_str_backup_phrase_and_private_key_desc":"確保它隱藏在離線物理設備上的安全位置。",

    //MARK:create wallet  -->
    "crazy_str_create":"創造",
    "crazy_str_mnemonic":"助記詞",
    "crazy_str_private_key":"私鑰",
    "crazy_str_copy":"複製",
    "crazy_str_create_wallet_desc":"您的 Secret Pecovery Phrase 讓備份和恢復變得容易",
    "crazy_str_verify_later":"稍後驗證",
    "crazy_str_confirm_right_now":"立即確認",

    //MARK:create import  -->
    "crazy_str_enter_mnemonics_or_secret_label":"輸入助記詞或私鑰",
    "crazy_str_enter_mnemonics_or_secret_desc":"用空格分隔助記符。支持12字助記詞導入，支持明文私鑰導入。",
    "crazy_str_import":"進口",
    "crazy_str_enter_mnemonics_or_secret_warning":"Warning: Use only Wallets Supporting",

    //MARK:back up  -->
    "crazy_str_backup":"備份",
    "crazy_str_backup_label":"備份你的錢包信息",
    "crazy_str_backup_desc":"您的 Secret Pecovery Phrase 可以輕鬆備份和恢復您的帳戶",
    "crazy_str_backup_hint":"用空格分隔助記符。支持12字助記詞導入，支持明文私鑰導入。",
    "crazy_str_backup_warning":"警告：切勿洩露您的秘密恢復短語。任何有這句話的人都可以永遠拿走你的資產",

    //MARK:back up confirm -->
    "crazy_str_backup_confirm":"備份確認",
    "crazy_str_backup_confirm_label":"驗證您的私鑰",
    "crazy_str_backup_confirm_desc":"請選擇每個單詞以確保其正確，並將其存儲在安全位置。",
    "crazy_str_backup_confirm_hint":"請輸入私鑰",
    "crazy_str_backup_confirm_warning":"警告：切勿洩露您的秘密恢復短語。任何有這句話的人都可以永遠拿走你的資產",

    //MARK:backup mnemonic verify -->
    "crazy_str_backup_mnemonic_verify_label":"驗證您的私鑰",
    "crazy_str_backup_mnemonic_verify_desc":"請選擇每個單詞以確保其正確，並將其存儲在安全位置。",

    //MARK:upgrade -->
    "crazy_str_upgrade_nft":"NFT升級",
    "crazy_str_choose_nft_to_upgrade":"選擇NFT升級",
    "crazy_str_empty":"空的",
    "crazy_str_empty_nfg_hint":"您的庫存中沒有可用的 NFT",
    "crazy_str_empty_nft_backpack_hint":"沒有有效的報價",
    "crazy_str_level_def":"Lv.%s",
    "crazy_str_switch":"轉化",
    "crazy_str_zero":"0",
    "crazy_str_nft_upgrade_desc":"",
    "crazy_str_max":"MAX",
    "crazy_str_speed_up":"加速",
    "crazy_str_buy":"買",
    "crazy_str_my_food_packs":"我的飼料包",
    "crazy_str_owned":"擁有",
    "crazy_str_level_up":"升級！",
    "crazy_str_upgrade":"進化！",
    "crazy_str_level":"等級",
    "crazy_str_hash":"Hash",

    //MARK: Dialog -->
    //MARK: set payment password -->
    "crazy_str_dialog_set_payment_password_desc":"系統發現您沒有為您的賬戶設置支付密碼。為了您的賬戶、錢包和資金安全，請設置支付密碼，以便日後操作。",
    "crazy_str_dialog_set_payment_password_btn":"現在設置！",
    //MARK: backup reminder -->
    "crazy_str_backup_reminder":"備份提醒",
    "crazy_str_skip":"跳過",
    "crazy_str_dialog_backup_reminder_desc":"您的錢包地址沒有為助記詞備份。為防止忘記密碼、刪除APP或丟失手機造成資產丟失，請務必備份助記詞！",

    //MARK: NFT Stake -->
    "crazy_str_nft_stake":"NFT權益",
    "crazy_str_all":"全部",
    "crazy_str_single":"單个",
    "crazy_str_set":"组",
    "crazy_str_total_hash_power":"總算力",
    "crazy_str_staked_amount":"質押金額",
    "crazy_str_my_hash_power":"我的算力",
    "crazy_str_staking_slot_bonus":"質押插槽獎金",
    "crazy_str_total_rewards":"總獎勵",
    "crazy_str_claims":"宣稱",
    "crazy_str_initial_hash_power":"初始算力",
    "crazy_str_set_hash_power_bonus":"設置哈希算力獎金",

    //MARK: Single Stake -->
    "crazy_str_choose_single_nft":"選擇單一 NFT",
    "crazy_str_choose_nft_set":"",
    "crazy_str_choose_nft_set_manual":"",
    "crazy_str_stake":"Stake",

    //MARK:market-->
    "crazy_str_market":"市場",
    "crazy_str_market_selling":"銷售",

    //MARK:NFT Lab-->
    "crazy_str_nft_lab":"NFT實驗室",
    "crazy_str_nft_level_up":"升級",
    "crazy_str_nft_upgrade":"進化",
    "crazy_str_nft_recycle":"轉換",
    "crazy_str_nft_transform":"轉換",
    "crazy_str_nft_incubation":"孵化",
    "crazy_str_nft_upgrade_orb":"升級寶珠",
    "crazy_str_nft_upgrade_stage":"升級階段",
    "crazy_str_nft_hash_bonus":"Hash bonus",
    "crazy_str_nft_choose_nft":"選擇NFT",
    "crazy_str_nft_choose_incubator":"選擇孵化器",
    "crazy_str_nft_incubation_time":"孵育時間：",
    "crazy_str_nft_Incubation_times":"孵化時間",
    "crazy_str_nft_incubation_time_desc":"",
    "crazy_str_nft_incubation_completed":"孵化完成",
    "crazy_str_nft_open":"打開",
    "crazy_str_nft_incubation_time_spent":"所花費的時間",
    "crazy_str_nft_incubation_end_time":"時間結束：",
    "crazy_str_nft_incubation_see_more":"<u>See more</u>",
    "crazy_str_nft_incubation_see_more_desc":"恭喜獲得一個NFT，更多內容見“我的NFT”",
    //MARK:my nft-->
    "crazy_str_my_nft":"我的 NFT",
    "crazy_str_nft_list":"NFT列表",
    "crazy_str_backpack":"背包",
    "crazy_str_upgrade_stage":"升級階段",
    "crazy_str_hash_power":"Hash Power",
    "crazy_str_sell":"賣",
    "crazy_str_use":"使用",

    //MARK:nft stake-->
    "crazy_str_nft_stake_list":"NFT 質押清單",
    "crazy_str_nft_stake_single_nft":"單個 NFT",
    "crazy_str_nft_stake_nft_set":"NFT 组合",
    "crazy_str_staking":"Staking",
    "crazy_str_empty_click_close":"點擊空白處關閉",
    "crazy_str_nft_stake_set_desc":"質押 NFT 集時，您至少需要 3 個不同質量的 NFT。",
    "crazy_str_nft_stake_my_nfts":"我的 NFT",
    "crazy_str_nft_stake_set_name":"設置名稱",
    "crazy_str_nft_stake_action":"行動",
    "crazy_str_claim":"宣稱",
    "crazy_str_stake_now":"現在質押",
    "crazy_str_set_needed":"需要設置",
    "crazy_str_select":"選擇",
    "crazy_str_selected":"已選",
    "crazy_str_start_time":"開始時間",
    "crazy_str_staking_earnings":"質押收益",
    "crazy_str_nft_sets":"NFT 套裝",
    "crazy_str_un_stakes":"未质押",

    //MARK:swap-->
    "crazy_str_swap":"交換",
    "crazy_str_pay":"支付",
    "crazy_str_get":"得到",
    "crazy_str_refresh_price":"刷新價格",
    "crazy_str_confirm_swap":"確認交換",
    "crazy_str_slippage":"滑移",
    "crazy_str_fees":"Fees",
    "crazy_str_conversion":"轉換",
    "crazy_str_price":"價格",
    "crazy_str_from":"從",
    "crazy_str_to":"到",
    //MARK:currency stake-->
    "crazy_str_token_stake":"令牌股份",
    "crazy_str_input_staking_amount":"輸入質押量",
    "crazy_str_select_time":"選擇時間",
    "crazy_str_cyt_quantity":"CYT 數量 (CYT)",
    "crazy_str_confirm_and_stake":"確認並質押",
    "crazy_str_apr_percent":"",
    "crazy_str_short":"短期",
    "crazy_str_meduim":"中期",
    "crazy_str_long":"長期",
    "crazy_str_7_day":"7天",
    "crazy_str_14_day":"14天",
    "crazy_str_1_month":"1個月",
    "crazy_str_3_month":"3個月",
    "crazy_str_6_month":"6個月",
    "crazy_str_1_year":"1年",
    "crazy_str_2_year":"2年",
    "crazy_str_3_year":"3年",


    "crazy_str_nft_details":"",
    "crazy_str_total_number_of_pledges":"認捐總數",
    "crazy_str_total_amount_of_cyt":"CYT總量",
    "crazy_str_receive_cyt_amount":"收到CYT金額：",
    "crazy_str_staking_time":"Staking time: ",
    "crazy_str_stake_start_time":"Stake start time:",
    "crazy_str_unlockin_time":"Unlocking time:",
    "crazy_str_my_token_stake":"My Token stake",
    "crazy_str_staking....":"Staking....",
    "crazy_str_estimated_fuel_cost":"Estimated Gas Fee Cost",
    "crazy_str_gas_fee":"Gas fee",
    "crazy_str_max_coins_needed":"Max Gas Coin needed",
    "crazy_str_remaining":"Remaining(GasCoin)",
    "crazy_str_contract_address":"合約地址",
    "crazy_str_reject":"拒絕",
    "crazy_str_confirm":"確認",
    "crazy_str_inventory_is_empty":"庫存為空",
    "crazy_str_transfer":"轉移",
    "crazy_str_approve":"批准",
    "crazy_str_un_staking":"解除質押",
    "crazy_str_see_your_nfts_here":"在這裡查看你的 NFT",
    "crazy_str_quantity_for_sale":"數量",
    "crazy_str_i_know":"我知道",
    "crazy_str_guide_desc":"單幣質押可以提供CYT。獲得CYT，即可在活動中以更低的價格獲得更優質的活動禮包。活動禮包內會包含一些優質的NFT或者高價值的材料道具",
    "crazy_str_guide_nft_stake_desc":"NFT質押分為個人質押和集合質押。任何閒置的 NFT 都可以單獨抵押。 Set Staking 需要同時質押同一組不同質量的 NFT。當集合滿足一定條件時，可以獲得算力紅利，獲得更多獎勵",
    "crazy_str_guide_token_stake_desc":"單幣質押可以提供CYT。獲得CYT，即可在活動中以更低的價格獲得更優質的活動禮包。活動禮包內會包含一些優質的NFT或者高價值的材料道具",
    "crazy_str_guide_wallet_desc":"在錢包中，可以查看自己目前擁有的資產，還可以進行一些備份、轉賬等操作。",
    "crazy_str_guide_level_up_desc":"升級可以提升NFT的等級。等級越高的NFT算力越高，質押NFT也可以獲得更高的收益",
    "crazy_str_guide_upgrade_desc":"進化可以提高 NFT 星級。星級越高，NFT算力紅利越高，質押NFT也可以獲得更高的收益",
    "crazy_str_guide_recycle_desc":"回收可以將閒置的NFT轉化為進化精華，可用於NFT的進化",
    "crazy_str_guide_incubation_desc":"使用兩個不同性別的NFT孵化，可以獲得一個全新的NFT。父母的質量越高，孵化出的 NFT 的質量就越高。",
    "crazy_str_guide_market_desc":" 1 新鑄造的NFT會有24小時的冷卻時間，冷卻時間內不能上幣交易市場 2 交易成功後會在交易市場收取3%的手續費 3 交易市場需要GASCOIN退市操作。 GASCOIN可在遊戲內通過兌換和購買鑽石獲得",


    //MARK:event-->
    "crazy_str_event":"活动",
    "crazy_str_gascoin":"Gascoin",
    "crazy_str_crazy_offers":"瘋狂優惠",
    "crazy_str_amount_left":"剩餘金額",
    "crazy_str_available":"可用的",
    "crazy_str_end_time":"事件時間：%s",
    "crazy_str_event_num":"",
    "crazy_str_event_old_price":"價格",
    "crazy_str_event_discount":"%s\noff",
    "crazy_str_event_buy":"買",
    "crazy_str_incubation_list_empty":"只能孵化8級以上的NFT",
    "crazy_str_token_stake_list_empty":"無代幣質押記錄",
    //MARK:-->
    "crazy_str_tip_application_init":"請在創建應用時請求，CrazyPlatform.init(this) 進行初始化",


    "crazy_str_day":"天",
    "crazy_str_month":"月",
    "crazy_str_year":"年",
    "crazy_str_tip_balance_empty":"餘額需要登錄",
    "crazy_str_tip_unknown_error":"未知錯誤",
    "crazy_str_tip_request_error":"請求失敗",
    "crazy_str_tip_data_gson_error":"數據解析錯誤，不符合預定格式",
    "crazy_str_tip_other_error":"未知錯誤",
    "crazy_str_tip_no_login":"未登錄",
    "crazy_str_tip_login_error":"登錄失敗，重試",
    "crazy_str_tip_wallet_chang":"切換錢包",
    "crazy_str_tip_blockchain_error":"區塊鏈錯誤",
    "crazy_str_tip_success":"成功",
    "crazy_str_tip_error":"錯誤",
    "crazy_str_to_unlock_slot_u_need":"要解鎖插槽，您需要：",
    "crazy_str_slot_card":"槽卡",
    "crazy_str_balance_":"平衡：",
    "crazy_str_unlock_slot_card":"",
    "crazy_str_balance_not_enough":"餘額不足",
    "crazy_str_place_offer":"報價",
    "crazy_str_change_price":"更改價格",
    "crazy_str_insufficient_inventory":"庫存不足",
    "crazy_str_current_purchasable_quantity":"當前可用數量為%s",
    "crazy_str_incubation":"孵育",
    "crazy_str_under_sale":"銷售",
    "crazy_str_At_least_three_or_more_can_pledged":"至少要抵押 3 個 NFT",
    "crazy_str_you_can_only_pledge":"最多允許6個staking slot~",
    "crazy_str_gas_coin_not_enough":"Gas Coin not enough",
    "crazy_str_data_cannot_be_empty":"數據不能為空~",
    "crazy_str_data_mismatch":"數據不符~",
    "crazy_str_inoperable":"無法操作~",
    "crazy_str_no_reward":"沒有獎勵~",
    "crazy_str_address_error":"地址錯誤~",
    "crazy_str_common_incubator":"普通孵化器",
    "crazy_str_good_incubator":"好孵化器",
    "crazy_str_excelent_incubator":"優秀孵化器",
    "crazy_str_rare_incubator":"珍稀孵化器",
    "crazy_str_epic_incubator":"史詩孵化器",
    "crazy_str_legendary_incubator":"傳奇孵化器",
    "crazy_str_upgrade_orb":"升級寶珠",
    "crazy_str_transform_orb":"變換寶珠",
    "crazy_str_simple_feed":"簡單飼料",
    "crazy_str_high_feed":"高進給",
    "crazy_str_super_feed":"超級飼料",
    "crazy_str_hourglass":"滴漏",
    "crazy_str_simple_box":"簡易盒子",
    "crazy_str_common_box":"普通盒",
    "crazy_str_good_box":"好箱子",
    "crazy_str_excellent_box":"優盒",
    "crazy_str_rare_box":"稀有盒子",
    "crazy_str_epic_box":"史詩盒子",
    "crazy_str_common_card_pack":"普通卡包",
    "crazy_str_incubation_for_common_nft":"孵化普通NFT",
    "crazy_str_incubation_for_good_nfts":"優秀 NFT 的孵化",
    "crazy_str_incubation_for_excellent_nft":"優秀NFT的孵化",
    "crazy_str_incubation_for_rare_nfts":"孵化稀有 NFT",
    "crazy_str_incubation_for_epic_nft":"史詩級 NFT 的孵化",
    "crazy_str_incubation_for_legend_nft":"孵化傳奇NFT",
    "crazy_str_consumable_materials_for_nft_evolution":"NFT進化的消耗材料",
    "crazy_str_nft_advanced_consumable_materials":"NFT高級消耗材料",
    "crazy_str_consumable_materials_for_nft_upgrades":"NFT升級消耗材料",
    "crazy_str_used_to_open_the_nft_staking_slot":"用於開啟NFT質押槽",
    "crazy_str_Accelerate_incubation_time_":"用於NFT孵化加速孵化時間",
    "crazy_str_super_cost_effective_mystery_box_":"超高性價比神秘盒子，100%普通NFT",
    "crazy_str_ordinary_quality_mystery_box_":"好神秘盒子掉落率：普通 - 10%，好 - 80%，高級飼料 - 10%",
    "crazy_str_good_quality_mystery_box_":"優秀的神秘盒子掉落率：良好 - 32%，優秀 - 68%",
    "crazy_str_excellent_quality_mystery_box_":"稀有神秘盒掉落率：良好 - 10%，優秀 - 50%，稀有 - 40%",
    "crazy_str_mystery_box_of_rare_quality_":"稀有神秘盒掉落率：良好 - 10%，優秀 - 50%，稀有 - 40%",
    "crazy_str_mystery_boxes_of_epic_quality_":"史詩神秘盒掉率：優秀 - 10%，稀有 - 60%，史詩 - 30%",
    "crazy_str_failed_to_load_click_retry":"加載失敗。點擊重試",
    "crazy_str_ball":"球",
    "crazy_str_item":"物品",
    "crazy_str_from_to":"從到",
    "crazy_str_time":"時間",
    "crazy_str_incubator":"孵化器",
    "crazy_str_incubating__":"孵化……",
    "crazy_str_congratulations_successful_incubation__":"恭喜您孵化成功！您剛剛收到一個新的 NFT。",
    "crazy_str_when_incubating_crazy":"在孵化 Crazy NFT 時，您可以使用沙漏來減少孵化時間。",


    "crazy_str_received":"已收到",
    "crazy_str_please_select_nft":"請選擇NFT~",
    "crazy_str_refresh":"刷新",
    "crazy_str_nft":"NFT",
    "crazy_str_props":"項目",
    "crazy_str_inventory":"存貨",
    "crazy_str_order_history":"訂單歷史",
    "crazy_str_quality":"質量",
    "crazy_str_reset":"重置",
    "crazy_str_gender":"性別",
    "crazy_str_boy":"男性",
    "crazy_str_girl":"女性",
    "crazy_str_empty_nft_list":"“沒有可顯示的 NFT。您可以通過以下方式獲得 NFT：1. 在 NFT 商店購買神秘盒子 2. 在市場上購買其他玩家的 NFT 3. 購買活動中定期出售的神秘盒子”",
    "crazy_str_orders_history":"訂單歷史",
    "crazy_str_data_of_swap":"掉期日期",
    "crazy_str_pay_pay":"支付",
    "crazy_str_get_get":"得到",
    "crazy_str_current_status":"當前狀態",
    "crazy_str_input_payment_password":"輸入支付密碼",
    "crazy_str_enter_the_password_to_verity":"輸入密碼驗證",
    "crazy_str_send_order":"發送訂單",
    "crazy_str_understand":"理解",
    "crazy_str_reviewing":"審閱",
    "crazy_str_waiting_for_blockchain_result_n":"等待\n區塊鏈結果",
    "crazy_str_waiting_for_blockchain_result":"等待區塊鏈結果",
    "crazy_str_confirming_transaction_n":"確認\n交易\n（預計到達時間 48 小時）",
    "crazy_str_confirming_transaction":"確認交易",
    "crazy_str_completed":"完全的",
    "crazy_str_cloose_single_nft":"關閉單個 NFT",
    "crazy_str_support_games":"支持遊戲",
    "crazy_str_in_process":"處理中",
    "crazy_str_finished":"完成的",
    "crazy_str_insufficient_gas_coin":"Insufficient Gas Coin",
    "crazy_str_insufficient_gas_coin_desc":"1. You can swap for Gas Coin in &quot;Swap&quot;\n2. You can swap for GasCoin with Diamond in game",
    "crazy_str_swap_now":"馬上換！",

    "crazy_str_help_nft_stake":"NFT Staking 可選擇單次或集合質押\n2 集合質押時，將根據所選NFT的質量和數量額外獲得質量加成\n 2.1 當一個質押集合中有3個不同質量的NFT時，一個可額外獲得20算力獎勵\n 2.2 當一個Stake集合中有4個不同質量的NFT時，可額外獲得50個算力獎勵\n 2.1 當一個Stake集合中有5個不同質量的NFT時，一個可額外獲得150算力獎勵\n 2.2 當一個Stake集合中有6個不同質量的NFT時，可額外獲得500算力獎勵\n3 NFT質押收益將按照您個人的比例進行分配hash power 池的總哈希 pwoer\n4 每日質押獎勵的數量由兩個因素決定。獎勵 = 質押 NFT 總算力（影響基礎獎勵）+ 平台遊戲活躍度（影響額外獎勵）\n5 質押 NFT 總算力影響基礎獎勵數量：\n 0-------- ---100000 總哈希將每天提供 6000 $Snake\n 100001------200000 總哈希將提供 10000 $Snake 每日獎勵\n 200001------300000 總哈希將提供 14000 $Snake 每日獎勵\n 300001-----500000 總哈希將提供 22000 $Snake 每日獎勵\n 500001-----750000 總哈希將提供 32000 $Snake 每日獎勵\n 750001-----1000000 總哈希將提供 40000 $Snake 每日獎勵\n 1000001-----3000000 總哈希將提供 124000 $Snake 每日獎勵\n 3000001-----6000000 總哈希將提供 232000 $Snake 每日獎勵\n 6000001---- -10000000 總哈希將提供 358000 $Snake 每日獎勵\n 10000001+----無限基礎獎勵 500000 $Snake\n6.平台遊戲活躍度影響額外獎勵：活躍度越高，額外獎勵越多",
    "crazy_str_help_incubation":"1孵化需要兩個不同性別的NFT進行孵化，\n2 NFT達到8級以上才能參與孵化。\n3每個NFT都有孵化次數限制。 NFT孵化次數為0時，該NFT將無法參與孵化\n4孵化需要使用孵化器。所使用孵化器的質量由選定的兩個NFT中質量最高的NFT決定。孵化器質量越高，孵化時間越長\n5 孵化過程中可以使用沙漏來縮短孵化時間",
    "crazy_str_help_recycle":"精華轉化可以將多餘的閒置NFT轉化為進化精華，進化精華可以用於NFT的進化，NFT進化後會獲得更多的算力加成\n2 NFT轉化為進化精華由NFT的算力決定本身和 NFT 的質量。算力越高，轉化的進化精華越多，轉化時根據NFT的好壞額外提供精華。",
    "crazy_str_help_token_stake":"1 當您質押您的$Snake代幣時，您可以選擇鎖定期。鎖定期結束後，您將獲得CYT。 CYT的數量決定了您在活動中可以購買平台禮包的個人訂閱數量。您擁有的 CYT 越多，您的購買力就越大。 \n2 當您質押的$snake鎖倉期結束後，您可以選擇提現質押金額，不會對生成的CYT產生任何影響",
    "crazy_str_help_swap_gas_coin":"1. 向區塊鏈發送請求產生gasfee，與區塊鏈平台原生token相關。\n2.為了方便，用戶可以使用GasCoin支付GasFee。",
    "crazy_str_help_event":"1. 活動中售賣的禮包數量有限，打折。\n2.您需要抵押 token 才能獲得 CYT，從而獲得購買資格。您擁有的 CYT 越多，您可以購買的禮包就越多。",
    "crazy_str_help_market":"》 1 新鑄造的 NFT 會有 24 小時的冷卻時間，在冷卻時間內不能上幣交易市場 2 交易成功後會在交易市場收取 3% 的手續費 3 交易市場需要 GASCOIN用於下線操作，GASCOIN可在遊戲內通過兌換和購買鑽石獲得”",

    "crazy_str_congratulations":"恭喜",
    "crazy_str_social":"社交",
    "crazy_str_support":"支持",
    "crazy_str_white_paper":"白皮書",
    "crazy_str_twitter":"推特",
    "crazy_str_discord":"Discord",
    "crazy_str_telegram":"Telegram",
    "crazy_str_type":"類型",
    "crazy_str_crazy_box":"瘋狂盒子",
    "crazy_str_purchase_how_many":"採購多少？",
    "crazy_str_no_available":"剩餘物品",
    "crazy_str_selling_price":"售價",
    "crazy_str_bought":"買",
    "crazy_str_sold":"賣",
    "crazy_str_confirming":"確認",
    "crazy_str_input_the_item_price":"輸入商品價格（美元）",
    "crazy_str_sell_how_many":"賣多少？",
    "crazy_str_sell_remove_offer":"移除報價",
    "crazy_str_sell_stopping":"停止",
    "crazy_str_staking_reward":"質押獎勵",
    "crazy_str_num_day":"%s 天",
    "crazy_str_num_month":"%s 月份",
    "crazy_str_num_year":"%s 年",
    "crazy_str_sell_stop":"記錄下來",
    "crazy_str_fighting":"鬥爭",
    "crazy_str_swap_u_min":"至少1 USDT才能繼續操作",
    "crazy_str_token_stake_min":"至少需要 200 $snake 才能繼續操作",
    "crazy_str_init_application":"請在打開時使用應用程序，執行 %s",


    //MARK:play2earn-->
    "crazy_str_play_2_earn":"Play2earn",
    "crazy_str_quest":"Quest",
    "crazy_str_withdraw":"Withdraw",
    "crazy_str_newcomer_benefits":"新人福利",
    "crazy_str_cash_value":"Cash value",
    "crazy_str_more_ways_to_get":"更多獲取方式",
    "crazy_str_back_to_game":"返回游戲",
    "crazy_str_watch_ads":"觀看廣告",
    "crazy_str_game_recharge":"遊戲充值",
    "crazy_str_invite_a_friend":"邀請朋友",
    "crazy_str_cyt":"CYT",
    "crazy_str_total_withdrawn":"總提现",
    "crazy_str_my_rewards":"我的獎勵",
    "crazy_str_my_invite_link":"我的邀請鏈接",
    "crazy_str_invite_via":"邀請方式",
    "crazy_str_today_rewards":"Today\'s Rewards",
    "crazy_str_see_more":"<u>See more</u>",
    "crazy_str_create_wallet":"創建錢包",
    "crazy_str_expected_to_receive":"預計收到",
    "crazy_str_withdraw_as":"提现为",
    "crazy_str_detailed_information":"詳細資料",
    "crazy_str_friend":"朋友",
    "crazy_str_shared_today":"今天分享",
    "crazy_str_total_shared":"共計分享",
    "crazy_str_direct_share":"直接共享 %s",
    "crazy_str_indirect_share":"間接份額 %s",
    "crazy_str_sure_to_proceed_with_the_conversion":"確定繼續轉換？",
    "crazy_str_help_swap_order_history_item_48h":"》1 兌換歷史中顯示的兌換時間以UTC時區為準，所以您在兌換歷史中看到的時間不是您所在時區的時間，您需要根據UTC時間確認您當前的進度2 接收資金的ETA時間是一種驗證平台內所有交易的方式，以確保兌換代幣的行為安全有效，我們不會挪用您的任何資產。”",


    "crazy_str_snake_token_required":"總需求",

    "crazy_str_share":"分享",
    "crazy_html_cash_value":"",
    "crazy_str_claimed":"聲稱",
    "crazy_str_earn_more":"得到更多",
    "crazy_str_watch_ads_desc":"“看廣告會產生一定的現金價值，這取決於廣告的value。”",
    "crazy_str_games_recharge_desc":"",
    "crazy_str_invite_a_friend_desc":"邀請好友領取更多獎勵",
    "crazy_str_invite_now":"現在邀請",
    "crazy_html_miss_total_withdraw_cash_value":"",
    "crazy_str_history":"歷史",
    "crazy_str_withdraw_history":"撤銷歷史",
    "crazy_str_date_of_withdraw":"退出日期",
    "crazy_str_withdraw_amount":"取款數量",
    "crazy_str_failed":"失敗的",
    "crazy_str_processing":"进度",
    "crazy_str_guess_the_size":"幸運色",
    "crazy_str_rank":"秩",
    "crazy_str_my_history":"我的歷史",
    "crazy_str_description":"描述",
    "crazy_html_red_time":"",
    "crazy_html_blue_time":"",
    "crazy_str_red":"紅色的",
    "crazy_str_blue":"藍色的",
    "crazy_str_bidding_area":"招標專區",
    "crazy_str_input_support_amount":"輸入支持量",
    "crazy_str_tip_support_agin":"暫時無法投注，請刷新重試～",
    "crazy_str_pool_size":"池大小",
    "crazy_str_countdown":"倒數",
    "crazy_str_round_ending_":"結尾",
    "crazy_str_round_no_open":"未開封",
    "crazy_str_round_opening":"開口",
    "crazy_str_luck_team":"幸運隊",
    "crazy_str_red_team":"紅隊",
    "crazy_str_blue_team":"藍隊",
    "crazy_str_random_value":"隨機值",
    "crazy_str_biggest_winner":"最大贏家",
    "crazy_str_bet_bonus":"投注/獎金",
    "crazy_str_my_bet":"我的賭注",
    "crazy_str_status":"地位",
    "crazy_str_claim_all":"索取所有",
    "crazy_str_get_luck":"獲得運氣",
    "crazy_str_no_luck":"沒有運氣",
    "crazy_str_haven_invited_friends_yet":"還沒有邀請朋友",
    "crazy_html_length_of_match":"",
    "crazy_str_no_rewards_claim":"沒有獎勵領取～",
    "crazy_str_no_records_to_show_at_the_moment":"沒有可顯示的記錄",
    "crazy_str_no_activty":"沒有活動",
    "crazy_html_when_nft_set_directions":"",
    "crazy_str_set_pets":"集寵物",
    "crazy_str_collected":"集",
    "crazy_str_bet_min_num":"投注金額不能小於%s",
    "crazy_str_bet_max_num":"投注金額不能大於%s",
    "crazy_str_bet_claim_num_min_max":"提現金額小於%s，無法提現",
    "crazy_str_help_guess_hot_play":"》火爆玩法：選擇一方參與。根據區塊鏈的智能合約預測對手的比分。預測數大小的來源由第三方預言機Chainlink提供，為比賽提供公平、簡單的環境。玩家。每輪比賽結束後決定勝負，通過Chainlink的Oracle獲得兩個隨機數，第一個為紅隊，第二個為藍隊。數字最大者獲勝。”",
    "crazy_str_help_share_cash_value":"&quot;1.現金價值是一種穩定幣，可以按固定比例兌換USDT。\n&quot; &quot;2.每次成功分享給朋友，您將獲得現金價值。當朋友從您的應用程序下載應用程序時分享鏈接，好友關係會自動綁定。\n&quot; &quot;3.當您邀請的好友和您好友分享的下一級好友在遊戲內觀看廣告和充值時，您將獲得額外的分享福利，您可以查看在“今日獎勵-查看更多”和“總獎勵-查看更多”\n&quot; &quot;4.成功綁定邀請關係：\n&quot; &quot;4.1新用戶未安裝瘋地平台設備\n &quot; &quot;4.2 創建錢包成功&quot;",

    "crazy_str_transfer_records":"轉賬記錄",
    "crazy_str_transfer_to":"傳送到",
    "crazy_str_amount":"數量",
    "crazy_str_in_development":"開發中。 . .",
    "crazy_str_insufficient_quota":"名額不足~",
    "crazy_str_view_more_details":"查看更多詳情",
    "crazy_str_shared_total":"共享總數",
    "crazy_str_portfolio":"文件夾",
    "crazy_str_deposit":"訂金",
    "crazy_str_after_listing":"列出您的 NFT 後，它將無法在遊戲中使用。使用我",
    "crazy_str_list_nft":"列出NFT",
    "crazy_str_my_wallet_address":"我的錢包地址",
    "crazy_str_gifted_wallet_address":"贈送錢包地址",
    "crazy_str_the_receiver_wallet_address":"接收方錢包地址必須是生態系統內部的錢包。",
    "crazy_str_send_now":"現在發送",
    "crazy_str_input_wallet_address":"輸入錢包地址",
    "crazy_str_address_format_is_incorrect":"地址格式不正確",
]

//class CS_Localized_CN: NSObject {
//
//}
